name: CI/CD Pipeline for Hadamu

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js 18.18.2
        uses: actions/setup-node@v3
        with:
          node-version: 18.18.2  # Replace with your desired Node.js version

      - name: Install dependencies
        run: npm install  # Or yarn install, if you use Yarn

      - name: Build Electron app
        run: npm run build  # Replace with your build command (e.g., electron-builder)
